<a href="https://colab.research.google.com/github/AbhignyaT/Machine_Learning/blob/main/ML_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
#1D Array
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
(5,)
1
<class 'numpy.ndarray'>


In [9]:
#0D Array
arr1=np.array(43)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

43
()
0


In [10]:
#2D array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [16]:
#3D array
arr3=np.array([[[1,2,1,2],[2,3,4,1]],[[2,4,5,1],[5,2,6,1]],[[2,6,1,7],[2,7,1,8]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 1 2]
  [2 3 4 1]]

 [[2 4 5 1]
  [5 2 6 1]]

 [[2 6 1 7]
  [2 7 1 8]]]
(3, 2, 4)
3


In [19]:
#n-D array
arr4=np.array([[1,2,3,4],[5,6,7,8]],ndmin=5)
print(arr4)
print('no of dim:',arr4.ndim)
print(arr4.shape)

[[[[[1 2 3 4]
    [5 6 7 8]]]]]
no of dim: 5
(1, 1, 1, 2, 4)


In [22]:
#Slicing arrays
print(arr1,arr[0],arr2[0][1],arr3[1][1][2])

print(arr1,arr[0],arr2[0,1],arr3[1,1,2])

43 1 2 6
43 1 2 6


In [24]:
#Slicing arrays negative indexing
print(arr2)
#print(arr2[-2][-1])
print(arr2[-2,-1])

[[1 2 3]
 [4 5 6]]
3
3


In [27]:
#Slicing 1D arr: [1,5]--> 1 to 4th index both included
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[2:]) #from 2 to end
print(arr4[:4]) #from start to 3rd index
print(arr4[-5:-1])  #-5 to -1 forward direction, [-1:-5]-->output: []
print(arr4[::2])  #alternatively

[3 4 5 6 7]
[1 2 3 4]
[3 4 5 6]
[1 3 5 7]


In [35]:
#Slicing 2D
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr5
print(arr5[1,1:4])
print(arr5[0:2,2])
print(arr5[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [36]:
print(arr5.dtype)

int64


In [39]:
arr6=np.array(['apple','banana','cherry'])
print(arr6.dtype) #gives the max length of the strings present

<U6


In [40]:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [45]:
arr=np.array(['1','2','3'],dtype='i') #cannot convert if['a','2','3']
print(arr)

[1 2 3]


In [47]:
#coverting data type
arr=np.array([3.45,2.141,4.15])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)
print(arr.dtype)

[3 2 4]
int32
float64


In [51]:
#Float to int by using "int"
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [53]:
#Copy
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [54]:
#View
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)
x[0]=125
print(arr) #change when made in view also reflects back in actual array

[42  2  3  4  5]
[42  2  3  4  5]
[125   2   3   4   5]


In [62]:
# Reshaping Arrays(1d->3d)
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [63]:
#Flattening the arrays(nd->1d)
arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [64]:
#Iterating arrays 1d
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In [65]:
#Iterating 2d
arr=np.array([[1,2,3], [4,5,6]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [66]:
#Iterating 3d
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [68]:
#Joining 2 arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [71]:
#Joining 2d arrays, axis=1
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)
#Joining 2d arrays, axis=0
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
#Splitting 1d into 3 parts
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


In [77]:
#Splitting 2-d
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,4)
print(newarr)
print(newarr[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]
[[1 2]
 [3 4]]


In [79]:
#Sorting Arrays
arr=np.array([3,2,0,1])
print(np.sort(arr))

arr1=np.array(['banana','cherry','apple'])
print(np.sort(arr1))

arr2=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr2))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


In [80]:
from numpy import random

In [82]:
x=random.randint(100)
print(x)
x1=random.rand()
print(x1)
x2=random.randint(100,size=(3,5))
print(x2)
x3=random.rand(3,5)
print(x3)

34
0.2567139238596231
[[87 68 74  8 37]
 [30 83 88 23 66]
 [51 46 32 76 67]]
[[0.52589366 0.0303731  0.80079213 0.68809165 0.83147191]
 [0.81494273 0.42370083 0.19368501 0.74095218 0.50578806]
 [0.99490509 0.07101594 0.49112153 0.89004967 0.45007878]]


In [84]:
#Array Aritmetic
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
b=np.array([[1,0,5],[2,3,7],[6,4,5]])
print(a+2)
print(a-1)
print(a*5)
print(a/2)

[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]
[[1.5 1.  2. ]
 [2.5 0.  0.5]
 [1.  2.5 4. ]]


In [85]:
c=a+b
print(c)
d=a-b
print(d)
e=a*b
print(e)

[[ 4  2  9]
 [ 7  3  8]
 [ 8  9 13]]
[[ 2  2 -1]
 [ 3 -3 -6]
 [-4  1  3]]
[[ 3  0 20]
 [10  0  7]
 [12 20 40]]


In [86]:
#Transpose of Array
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
print(a)
ta=np.transpose(a)
print(ta)

[[3 2 4]
 [5 0 1]
 [2 5 8]]
[[3 5 2]
 [2 0 5]
 [4 1 8]]


In [87]:
#Mean Median SD
a= np.arange(5,50,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean : 27.0
Standard deviation : 13.2664991614216
Median : 27.0


In [88]:
#Min along col
print('Min:',np.min(a))
#Max along row
print('Max:',np.max(a))

Min: 5
Max: 49


In [89]:
#Min and Max with 2D
a = np.array([[3,2,4], [10,0,1], [7,5,8]])
print(a)
print('Min :',np.min(a, axis=0))
print('Max :',np.max(a, axis=1))

[[ 3  2  4]
 [10  0  1]
 [ 7  5  8]]
Min : [3 0 1]
Max : [ 4 10  8]


In [90]:
#Random Distribution
x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(100))
print(x)
y = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(3,5))
print(y)
# Normal Distribution
x = random.normal(size=(2,3))
print(x)
y = random.normal(loc=1, scale=2, size=(2,3))
print(y)

[7 5 7 7 7 7 5 7 5 7 7 7 7 5 7 3 3 7 5 5 7 7 5 5 7 5 7 7 5 7 5 7 7 3 3 7 7
 7 7 7 7 3 5 7 7 7 7 3 5 7 5 5 7 5 5 7 7 5 7 7 7 7 7 7 5 7 5 7 7 7 7 3 5 5
 7 7 7 7 5 7 3 3 5 5 7 7 7 5 7 5 3 7 5 7 5 7 7 5 7 7]
[[7 7 7 7 3]
 [5 5 7 7 7]
 [7 5 7 7 5]]
[[-0.90684605 -0.53248531 -0.37231791]
 [-0.24739884 -0.28578601 -0.14827794]]
[[ 2.49958777  1.91975701 -1.80775264]
 [-0.49166208 -0.89638219 -1.38929906]]
